<?php
namespace Tuezy;

use Illuminate\Foundation\Application;

class EE extends Application{

    public function getNamespace()
    {
        return "Tuezy"; // TODO: Change the autogenerated stub
    }


}